### ISSUE TITLE
Actividad_02 Realidad Aumentada Con Objeto 3D

### ISSUE THREAD

**Issue by ArteezyOne** [SistemasTecTlaxiaco/realidad-aumentada-objeto-3d-joel#2]
[Actividad-02-Realidad_Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/realidad-aumentada-objeto-3d-joel/files/6192598/Actividad-02-Realidad_Aumentada.pdf)

**Comment by Itzelzun** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y realizado.
